version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=starter_template
      - POSTGRES_USER=admin
      - POSTGRES_DB=starter
